# Generated by Django 3.2.25 on 2024-09-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sageadvice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
